use_frameworks!
platform :ios, '9.0'
platform :tvos, '10.0'

target 'MyAwesomeLib_Example' do	
end

target 'MyAwesomeLib_Tests' do
    inherit! :search_paths
    pod 'MyAwesomeLib', :path => '../'
    
end
