use_frameworks!

target 'MyAwesomeLib_Example' do
  pod 'MyAwesomeLib', :git => 'https://github.com/SeverinetsDenis/MyAwesomeLib', :branch => 'master'

  target 'MyAwesomeLib_Tests' do
    inherit! :search_paths

    
  end
end
